/**
 * User mapping between Favro usernames and Slack user IDs
 * Generated by setup-user-mapping.ts on 2025-07-09T14:12:26.622Z
 */
import { UserMapping } from '../types';

/**
 * Maps Favro usernames to Slack user IDs
 * Format: { 'favroUsername': 'slackUserId' }
 */
export const userMapping: UserMapping = {
  "Adam Svensson": "U91238WEOBY",
  "Erik Almqvist": "U094YFADS29"
};
